name: Deploy Zaurio Roulette

on:
  push:
    branches: [ main ]
    paths:
      - 'overlays/zaurio-roulette/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy overlay via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            set -e
            # ensure repo is on the server
            if [ -d "$HOME/site/.git" ]; then
              cd $HOME/site && git pull
            else
              git clone https://github.com/azurionte/azurionte.es.git $HOME/site
            fi

            cd $HOME/site/overlays/zaurio-roulette

            # install node/npm if missing (Ubuntu/Debian)
            if ! command -v node >/dev/null 2>&1; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get update
              sudo apt-get install -y nodejs build-essential
            fi

            # ensure pm2
            sudo npm install -g pm2 || true

            # install deps and start app with pm2
            npm install
            sudo pm2 start ecosystem.config.js --name zaurio-roulette --update-env || sudo pm2 restart zaurio-roulette || sudo pm2 start ecosystem.config.js --name zaurio-roulette
            sudo pm2 save

            # write nginx config (overwrites /etc/nginx/sites-available/azurionte.es)
            sudo tee /etc/nginx/sites-available/azurionte.es > /dev/null <<'NGINX'
server {
  listen 80;
  server_name azurionte.es www.azurionte.es;
  root /var/www/site;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }

  location /overlays/zaurio-roulette/ {
    proxy_pass http://127.0.0.1:8080/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_buffering off;
  }
}
NGINX

            sudo ln -sf /etc/nginx/sites-available/azurionte.es /etc/nginx/sites-enabled/azurionte.es
            sudo nginx -t
            sudo systemctl reload nginx

            # install certbot and request TLS certificates (non-interactive)
            if ! command -v certbot >/dev/null 2>&1; then
              sudo apt-get install -y certbot python3-certbot-nginx
            fi
            sudo certbot --nginx -n --agree-tos --email "${{ secrets.LETSENCRYPT_EMAIL }}" -d azurionte.es -d www.azurionte.es || true
